// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH A MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToPeer(arg1) {
  return window['go']['main']['App']['ConnectToPeer'](arg1);
}

export function CreateWallet() {
  return window['go']['main']['App']['CreateWallet']();
}

export function GetBalance() {
  return window['go']['main']['App']['GetBalance']();
}

export function GetBlock(arg1) {
  return window['go']['main']['App']['GetBlock'](arg1);
}

export function GetChainHeight() {
  return window['go']['main']['App']['GetChainHeight']();
}

export function GetPeerCount() {
  return window['go']['main']['App']['GetPeerCount']();
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function GetPendingTxCount() {
  return window['go']['main']['App']['GetPendingTxCount']();
}

export function GetRecentBlocks(arg1) {
  return window['go']['main']['App']['GetRecentBlocks'](arg1);
}

export function GetWalletInfo() {
  return window['go']['main']['App']['GetWalletInfo']();
}

export function Mine() {
  return window['go']['main']['App']['Mine']();
}

export function SendTransaction(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendTransaction'](arg1, arg2, arg3);
}
