// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH A MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToPeer(arg1:string):Promise<Record<string, string>>;

export function CreateWallet():Promise<Record<string, string>>;

export function GetBalance():Promise<Record<string, any>>;

export function GetBlock(arg1:number):Promise<Record<string, any>>;

export function GetChainHeight():Promise<number>;

export function GetPeerCount():Promise<number>;

export function GetPeers():Promise<string[]>;

export function GetPendingTxCount():Promise<number>;

export function GetRecentBlocks(arg1:number):Promise<Record<string, any>[]>;

export function GetWalletInfo():Promise<Record<string, string>>;

export function Mine():Promise<Record<string, any>>;

export function SendTransaction(arg1:string,arg2:number,arg3:number):Promise<Record<string, string>>;
